# Generated by Django 2.0.5 on 2018-06-27 02:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('idname', models.CharField(max_length=20)),
                ('passwd', models.CharField(max_length=20)),
                ('name', models.CharField(max_length=20)),
                ('groupname', models.CharField(max_length=20)),
                ('phonenumber', models.CharField(max_length=20)),
                ('is_supervisor', models.BooleanField()),
                ('cdate', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
