# Generated by Django 2.1 on 2018-11-12 08:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0002_loginuser'),
    ]

    operations = [
        migrations.CreateModel(
            name='waituser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('idname', models.CharField(max_length=20)),
                ('passwd', models.CharField(max_length=20)),
                ('name', models.CharField(max_length=20)),
                ('groupname', models.CharField(max_length=20)),
                ('phonenumber', models.CharField(max_length=20)),
                ('cdate', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
