# Generated by Django 2.1 on 2018-11-23 07:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0003_waituser'),
    ]

    operations = [
        migrations.CreateModel(
            name='version',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('v', models.IntegerField()),
                ('hash', models.CharField(max_length=100)),
            ],
        ),
    ]
