# Generated by Django 2.1 on 2018-11-23 05:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('info', '0002_remove_process_disk'),
    ]

    operations = [
        migrations.AlterField(
            model_name='process',
            name='cpu',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='process',
            name='memory',
            field=models.FloatField(),
        ),
    ]
