# Generated by Django 2.1 on 2018-11-23 07:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('info', '0004_disk'),
    ]

    operations = [
        migrations.AlterField(
            model_name='process',
            name='pname',
            field=models.CharField(max_length=100),
        ),
    ]
